from PyQt5 import QtWidgets, QtCore
from utilities import customized_widgets as cw


class ConWidget(QtWidgets.QWidget):
    Signal_piezo_move = QtCore.pyqtSignal()
    Signal_deck_up = QtCore.pyqtSignal()
    Signal_deck_down = QtCore.pyqtSignal()
    Signal_deck_move = QtCore.pyqtSignal()
    Signal_deck_move_stop = QtCore.pyqtSignal()
    Signal_setcoordinates = QtCore.pyqtSignal()
    Signal_resetcoordinates = QtCore.pyqtSignal()
    Signal_setbin = QtCore.pyqtSignal()
    Signal_setlaseron_488_0 = QtCore.pyqtSignal()
    Signal_setlaseron_488_1 = QtCore.pyqtSignal()
    Signal_setlaseron_488_2 = QtCore.pyqtSignal()
    Signal_setlaseron_405 = QtCore.pyqtSignal()
    Signal_setlaseroff_488_0 = QtCore.pyqtSignal()
    Signal_setlaseroff_488_1 = QtCore.pyqtSignal()
    Signal_setlaseroff_488_2 = QtCore.pyqtSignal()
    Signal_setlaseroff_405 = QtCore.pyqtSignal()
    Signal_start_video = QtCore.pyqtSignal()
    Signal_stop_video = QtCore.pyqtSignal()
    Signal_run_fft = QtCore.pyqtSignal()
    Signal_stop_fft = QtCore.pyqtSignal()
    Signal_2d_resolft = QtCore.pyqtSignal()
    Signal_3d_resolft = QtCore.pyqtSignal()
    Signal_beadscan_2d = QtCore.pyqtSignal()
    Signal_save_file = QtCore.pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)

        layout = QtWidgets.QVBoxLayout()
        Group_CCDCamera = cw.group_widget('CCD Camera')
        Group_PiezoStage = cw.group_widget('Piezo Stage')
        Group_MadDeck = cw.group_widget('Mad Deck')
        Group_Illumination = cw.group_widget('Laser')
        Group_DataAquisition = cw.group_widget('Image Acquisition ')
        Group_Triggers = cw.group_widget('Triggers')
        Group_File = cw.group_widget('File')
        layout.addStretch()
        layout.addWidget(Group_CCDCamera)
        layout.addWidget(Group_PiezoStage)
        layout.addWidget(Group_MadDeck)
        layout.addWidget(Group_Illumination)
        layout.addWidget(Group_DataAquisition)
        layout.addWidget(Group_Triggers)
        layout.addWidget(Group_File)
        layout.addStretch()
        self.setLayout(layout)

        Layout_MainCamera = QtWidgets.QGridLayout()
        self.QLabel_ccd_tempetature = cw.label_widget(str('CCD Temperature'))
        self.QLCDNumber_ccd_tempetature = cw.lcdnumber_widget()
        self.QLabel_coordinate_x = cw.label_widget(str('X'))
        self.QSpinBox_coordinate_x = cw.spinbox_widget(0, 2048, 1, 1)
        self.QLabel_coordinate_y = cw.label_widget(str('Y'))
        self.QSpinBox_coordinate_y = cw.spinbox_widget(0, 2048, 1, 1)
        self.QLabel_coordinate_n = cw.label_widget(str('N'))
        self.QSpinBox_coordinate_n = cw.spinbox_widget(0, 2048, 1, 1024)
        self.QLabel_coordinate_bin = cw.label_widget(str('Bin'))
        self.QSpinBox_coordinate_bin = cw.spinbox_widget(0, 1024, 1, 1)
        self.QPushButton_setcoordinates = cw.pushbutton_widget('SetCoord')
        self.QPushButton_resetcoordinates = cw.pushbutton_widget('ResetCoord')
        Layout_MainCamera.addWidget(self.QLabel_ccd_tempetature, 0, 0, 1, 1)
        Layout_MainCamera.addWidget(self.QLCDNumber_ccd_tempetature, 0, 1, 1, 1)
        Layout_MainCamera.addWidget(self.QLabel_coordinate_x, 2, 0, 1, 1)
        Layout_MainCamera.addWidget(self.QSpinBox_coordinate_x, 3, 0, 1, 1)
        Layout_MainCamera.addWidget(self.QLabel_coordinate_y, 2, 1, 1, 1)
        Layout_MainCamera.addWidget(self.QSpinBox_coordinate_y, 3, 1, 1, 1)
        Layout_MainCamera.addWidget(self.QLabel_coordinate_n, 2, 2, 1, 1)
        Layout_MainCamera.addWidget(self.QSpinBox_coordinate_n, 3, 2, 1, 1)
        Layout_MainCamera.addWidget(self.QLabel_coordinate_bin, 2, 3, 1, 1)
        Layout_MainCamera.addWidget(self.QSpinBox_coordinate_bin, 3, 3, 1, 1)
        Layout_MainCamera.addWidget(self.QPushButton_setcoordinates, 4, 0, 1, 1)
        Layout_MainCamera.addWidget(self.QPushButton_resetcoordinates, 4, 1, 1, 1)
        Group_CCDCamera.setLayout(Layout_MainCamera)

        Layout_mad_deck = QtWidgets.QGridLayout()
        self.QLabel_deck_position = cw.label_widget(str('Position (mm)'))
        self.QLCDNumber_deck_position = cw.lcdnumber_widget()
        self.QLabel_deck_move_fine = cw.label_widget(str('Fine step'))
        self.QPushButton_move_deck_up = cw.pushbutton_widget('Up')
        self.QPushButton_move_deck_down = cw.pushbutton_widget('Down')
        self.QLabel_deck_movement = cw.label_widget(str('Distance (mm)'))
        self.QDoubleSpinBox_deck_movement = cw.doublespinbox_widget(-11.5, 11.5, 0.001, 3, 0.01)
        self.QLabel_deck_velocity = cw.label_widget(str('Velocity (mm)'))
        self.QDoubleSpinBox_deck_velocity = cw.doublespinbox_widget(0.02, 1.50, 0.02, 2, 0.02)
        self.QPushButton_move_deck = cw.pushbutton_widget('Move')
        self.QPushButton_move_deck_stop = cw.pushbutton_widget('STOP')
        Layout_mad_deck.addWidget(self.QLabel_deck_position, 0, 0, 1, 1)
        Layout_mad_deck.addWidget(self.QLCDNumber_deck_position, 1, 0, 1, 1)
        Layout_mad_deck.addWidget(self.QLabel_deck_move_fine, 0, 2, 1, 1)
        Layout_mad_deck.addWidget(self.QPushButton_move_deck_up, 1, 2, 1, 1)
        Layout_mad_deck.addWidget(self.QPushButton_move_deck_down, 2, 2, 1, 1)
        Layout_mad_deck.addWidget(self.QLabel_deck_movement, 0, 1, 1, 1)
        Layout_mad_deck.addWidget(self.QDoubleSpinBox_deck_movement, 1, 1, 1, 1)
        # Layout_mad_deck.addWidget(self.QLabel_deck_velocity, 0, 1, 1, 1)
        # Layout_mad_deck.addWidget(self.QDoubleSpinBox_deck_velocity, 1, 1, 1, 1)
        Layout_mad_deck.addWidget(self.QPushButton_move_deck, 2, 0, 1, 1)
        Layout_mad_deck.addWidget(self.QPushButton_move_deck_stop, 2, 1, 1, 1)
        Group_MadDeck.setLayout(Layout_mad_deck)

        Layout_piezo_stage = QtWidgets.QGridLayout()
        self.QLabel_stage_x = cw.label_widget(str('X (um)'))
        self.QDoubleSpinBox_stage_x = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.00)
        self.QLCDNumber_stage_x = cw.lcdnumber_widget()
        self.QLabel_stage_y = cw.label_widget(str('Y (um)'))
        self.QDoubleSpinBox_stage_y = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.00)
        self.QLCDNumber_stage_y = cw.lcdnumber_widget()
        self.QLabel_stage_z = cw.label_widget(str('Z (um)'))
        self.QDoubleSpinBox_stage_z = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.00)
        self.QLCDNumber_stage_z = cw.lcdnumber_widget()
        Layout_piezo_stage.addWidget(self.QLabel_stage_x, 0, 0, 1, 1)
        Layout_piezo_stage.addWidget(self.QDoubleSpinBox_stage_x, 1, 0, 1, 1)
        Layout_piezo_stage.addWidget(self.QLCDNumber_stage_x, 2, 0, 1, 1)
        Layout_piezo_stage.addWidget(self.QLabel_stage_y, 0, 1, 1, 1)
        Layout_piezo_stage.addWidget(self.QDoubleSpinBox_stage_y, 1, 1, 1, 1)
        Layout_piezo_stage.addWidget(self.QLCDNumber_stage_y, 2, 1, 1, 1)
        Layout_piezo_stage.addWidget(self.QLabel_stage_z, 0, 2, 1, 1)
        Layout_piezo_stage.addWidget(self.QDoubleSpinBox_stage_z, 1, 2, 1, 1)
        Layout_piezo_stage.addWidget(self.QLCDNumber_stage_z, 2, 2, 1, 1)
        Group_PiezoStage.setLayout(Layout_piezo_stage)

        Layout_Illumination = QtWidgets.QGridLayout()
        self.QRadioButton_laser_488_0 = cw.radiobutton_widget('Laser 488 nm #0')
        self.QDoubleSpinBox_laserpower_488_0 = cw.doublespinbox_widget(0, 100, 0.1, 1, 0.0)
        self.QPushButton_laser_488_0 = cw.pushbutton_widget('ON', checkable=True)
        self.QRadioButton_laser_488_1 = cw.radiobutton_widget('Laser 488 nm #1')
        self.QDoubleSpinBox_laserpower_488_1 = cw.doublespinbox_widget(0, 100, 0.1, 1, 0.0)
        self.QPushButton_laser_488_1 = cw.pushbutton_widget('ON', checkable=True)
        self.QRadioButton_laser_488_2 = cw.radiobutton_widget('Laser 488 nm #2')
        self.QDoubleSpinBox_laserpower_488_2 = cw.doublespinbox_widget(0, 100, 0.1, 1, 0.0)
        self.QPushButton_laser_488_2 = cw.pushbutton_widget('ON', checkable=True)
        self.QRadioButton_laser_405 = cw.radiobutton_widget('Laser 405 nm')
        self.QDoubleSpinBox_laserpower_405 = cw.doublespinbox_widget(0, 100, 0.1, 1, 0.0)
        self.QPushButton_laser_405 = cw.pushbutton_widget('ON', checkable=True)
        Layout_Illumination.addWidget(self.QRadioButton_laser_488_0, 0, 0, 1, 1)
        Layout_Illumination.addWidget(self.QDoubleSpinBox_laserpower_488_0, 0, 1, 1, 1)
        Layout_Illumination.addWidget(self.QPushButton_laser_488_0, 0, 2, 1, 1)
        Layout_Illumination.addWidget(self.QRadioButton_laser_488_1, 1, 0, 1, 1)
        Layout_Illumination.addWidget(self.QDoubleSpinBox_laserpower_488_1, 1, 1, 1, 1)
        Layout_Illumination.addWidget(self.QPushButton_laser_488_1, 1, 2, 1, 1)
        Layout_Illumination.addWidget(self.QRadioButton_laser_488_2, 2, 0, 1, 1)
        Layout_Illumination.addWidget(self.QDoubleSpinBox_laserpower_488_2, 2, 1, 1, 1)
        Layout_Illumination.addWidget(self.QPushButton_laser_488_2, 2, 2, 1, 1)
        Layout_Illumination.addWidget(self.QRadioButton_laser_405, 3, 0, 1, 1)
        Layout_Illumination.addWidget(self.QDoubleSpinBox_laserpower_405, 3, 1, 1, 1)
        Layout_Illumination.addWidget(self.QPushButton_laser_405, 3, 2, 1, 1)
        Group_Illumination.setLayout(Layout_Illumination)

        Layout_DataAquisition = QtWidgets.QGridLayout()
        self.QLabel_exposure_time = cw.label_widget(str('Exposure Time (s)'))
        self.QDoubleSpinBox_exposure_time = cw.doublespinbox_widget(0, 10, 0.005, 3, 0.02)
        self.QLabel_emccd_gain = cw.label_widget(str('EMCCD Gain'))
        self.QSpinBox_emccd_gain = cw.spinbox_widget(0, 300, 1, 0)
        self.QPushButton_start_video = cw.pushbutton_widget('Video')
        self.QPushButton_stop_video = cw.pushbutton_widget('Stop')
        self.QPushButton_singlesnap = cw.pushbutton_widget('SingleSnap')
        self.QPushButton_start_fft = cw.pushbutton_widget('Run FFT')
        self.QPushButton_stop_fft = cw.pushbutton_widget('Stop FFT')
        Layout_DataAquisition.addWidget(self.QLabel_exposure_time, 0, 0, 1, 1)
        Layout_DataAquisition.addWidget(self.QDoubleSpinBox_exposure_time, 0, 1, 1, 1)
        Layout_DataAquisition.addWidget(self.QLabel_emccd_gain, 1, 0, 1, 1)
        Layout_DataAquisition.addWidget(self.QSpinBox_emccd_gain, 1, 1, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_start_video, 2, 0, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_stop_video, 2, 1, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_singlesnap, 2, 2, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_start_fft, 3, 0, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_stop_fft, 3, 1, 1, 1)
        Group_DataAquisition.setLayout(Layout_DataAquisition)

        Layout_Triggers = QtWidgets.QGridLayout()
        self.QLabel_cycle_period = cw.label_widget(str('Cycle period / s'))
        self.QDoubleSpinBox_cycle_period = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.1)
        self.QLabel_piezo_start = cw.label_widget(str('Piezo_start / s'))
        self.QDoubleSpinBox_piezo_start = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.075)
        self.QLabel_start_positions = cw.label_widget(str('Start_positions / um'))
        self.QLabel_step_sizes = cw.label_widget(str('Step_sizes / um'))
        self.QLabel_scan_ranges = cw.label_widget(str('Scan_ranges / um'))
        self.QLabel_axis_x = cw.label_widget(str('X'))
        self.QLabel_axis_y = cw.label_widget(str('Y'))
        self.QLabel_axis_z = cw.label_widget(str('Z'))
        self.QDoubleSpinBox_start_x = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.000)
        self.QDoubleSpinBox_start_y = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.000)
        self.QDoubleSpinBox_start_z = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.000)
        self.QDoubleSpinBox_step_x = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.040)
        self.QDoubleSpinBox_step_y = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.040)
        self.QDoubleSpinBox_step_z = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.080)
        self.QDoubleSpinBox_range_x = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.400)
        self.QDoubleSpinBox_range_y = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.400)
        self.QDoubleSpinBox_range_z = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.800)
        self.QLabel_ttl_starts = cw.label_widget(str('TTL_starts / s'))
        self.QLabel_ttl_stops = cw.label_widget(str('TTL_stops / s'))
        self.QLabel_ttl_on_405 = cw.label_widget(str('On 405'))
        self.QLabel_ttl_off_488_0 = cw.label_widget(str('Off 488_0'))
        self.QLabel_ttl_off_488_1 = cw.label_widget(str('Off 488_1'))
        self.QLabel_ttl_read_488_2 = cw.label_widget(str('Read 488_2'))
        self.QLabel_ttl_camera = cw.label_widget(str('Camera'))
        self.QDoubleSpinBox_ttl_start_on_405 = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.005)
        self.QDoubleSpinBox_ttl_start_off_488_0 = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.020)
        self.QDoubleSpinBox_ttl_start_off_488_1 = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.020)
        self.QDoubleSpinBox_ttl_start_read_488_2 = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.040)
        self.QDoubleSpinBox_ttl_start_camera = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.040)
        self.QDoubleSpinBox_ttl_stop_on_405 = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.015)
        self.QDoubleSpinBox_ttl_stop_off_488_0 = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.035)
        self.QDoubleSpinBox_ttl_stop_off_488_1 = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.035)
        self.QDoubleSpinBox_ttl_stop_read_488_2 = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.060)
        self.QDoubleSpinBox_ttl_stop_camera = cw.doublespinbox_widget(0, 1, 0.001, 3, 0.060)
        self.QLabel_trigger_parameter = cw.label_widget(str('Pre-sets'))
        self.QComboBox_trigger_parameter = cw.combobox_widget(list_items=['Default', 'UseDefined_1', 'UseDefined_2'])
        self.QPushButton_2d_resolft = cw.pushbutton_widget('2D_RESOLFT')
        self.QPushButton_3d_resolft = cw.pushbutton_widget('3D_RESOLFT')
        self.QPushButton_2d_beadscan = cw.pushbutton_widget('2D_BeadScan')
        Layout_Triggers.addWidget(self.QLabel_cycle_period, 0, 0, 1, 2)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_cycle_period, 1, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_piezo_start, 0, 2, 1, 2)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_piezo_start, 1, 2, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_trigger_parameter, 0, 4, 1, 2)
        Layout_Triggers.addWidget(self.QComboBox_trigger_parameter, 1, 4, 1, 2)
        Layout_Triggers.addWidget(self.QLabel_step_sizes, 4, 0, 1, 2)
        Layout_Triggers.addWidget(self.QLabel_scan_ranges, 5, 0, 1, 2)
        Layout_Triggers.addWidget(self.QLabel_axis_x, 2, 2, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_axis_y, 2, 3, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_axis_z, 2, 4, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_start_x, 3, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_start_y, 3, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_start_z, 3, 4, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_step_x, 4, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_step_y, 4, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_step_z, 4, 4, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_range_x, 5, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_range_y, 5, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_range_z, 5, 4, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_starts, 7, 0, 1, 2)
        Layout_Triggers.addWidget(self.QLabel_ttl_stops, 8, 0, 1, 2)
        Layout_Triggers.addWidget(self.QLabel_ttl_on_405, 6, 2, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_off_488_0, 6, 3, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_off_488_1, 6, 4, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_read_488_2, 6, 5, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_camera, 6, 6, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_on_405, 7, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_off_488_0, 7, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_off_488_1, 7, 4, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_read_488_2, 7, 5, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_camera, 7, 6, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_on_405, 8, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_off_488_0, 8, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_off_488_1, 8, 4, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_read_488_2, 8, 5, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_camera, 8, 6, 1, 1)
        Layout_Triggers.addWidget(self.QPushButton_2d_beadscan, 9, 0, 1, 2)
        Layout_Triggers.addWidget(self.QPushButton_2d_resolft, 9, 2, 1, 2)
        Layout_Triggers.addWidget(self.QPushButton_3d_resolft, 9, 4, 1, 2)
        Group_Triggers.setLayout(Layout_Triggers)

        Layout_File = QtWidgets.QGridLayout()
        self.QLabel_file_name = cw.label_widget(str('File name'))
        self.QLineEdit_filename = cw.lineedit_widget()
        self.QPushButton_save = cw.pushbutton_widget('Save')
        Layout_File.addWidget(self.QLabel_file_name, 0, 0, 1, 1)
        Layout_File.addWidget(self.QLineEdit_filename, 0, 1, 1, 4)
        Layout_File.addWidget(self.QPushButton_save, 0, 5, 1, 1)
        Group_File.setLayout(Layout_File)

        self.QPushButton_setcoordinates.clicked.connect(self.set_coordinates)
        self.QPushButton_resetcoordinates.clicked.connect(self.reset_coordinates)
        self.QDoubleSpinBox_stage_x.valueChanged.connect(self.piezo_move)
        self.QDoubleSpinBox_stage_y.valueChanged.connect(self.piezo_move)
        self.QDoubleSpinBox_stage_z.valueChanged.connect(self.piezo_move)
        self.QPushButton_move_deck_up.clicked.connect(self.deck_move_up)
        self.QPushButton_move_deck_down.clicked.connect(self.deck_move_down)
        self.QPushButton_move_deck.clicked.connect(self.deck_move)
        self.QPushButton_move_deck_stop.clicked.connect(self.deck_move_stop)
        self.QPushButton_start_video.clicked.connect(self.start_video)
        self.QPushButton_stop_video.clicked.connect(self.stop_video)
        self.QPushButton_start_fft.clicked.connect(self.run_ft)
        self.QPushButton_stop_fft.clicked.connect(self.stop_ft)
        self.QPushButton_save.clicked.connect(self.save)
        self.QPushButton_laser_488_0.clicked.connect(self.set_laser_488_0)
        self.QPushButton_laser_488_1.clicked.connect(self.set_laser_488_1)
        self.QPushButton_laser_488_2.clicked.connect(self.set_laser_488_2)
        self.QPushButton_laser_405.clicked.connect(self.set_laser_405)
        self.QPushButton_2d_resolft.clicked.connect(self.resolft_2d)
        self.QPushButton_3d_resolft.clicked.connect(self.resolft_3d)
        self.QPushButton_2d_beadscan.clicked.connect(self.beadscan_2d)
        self.QComboBox_trigger_parameter.currentIndexChanged.connect(self.update_trigger_parameter_sets)

    def set_laser_488_0(self):
        if self.QPushButton_laser_488_0.isChecked():
            self.Signal_setlaseron_488_0.emit()
        else:
            self.Signal_setlaseroff_488_0.emit()

    def set_laser_488_1(self):
        if self.QPushButton_laser_488_1.isChecked():
            self.Signal_setlaseron_488_1.emit()
        else:
            self.Signal_setlaseroff_488_1.emit()

    def set_laser_488_2(self):
        if self.QPushButton_laser_488_2.isChecked():
            self.Signal_setlaseron_488_2.emit()
        else:
            self.Signal_setlaseroff_488_2.emit()

    def set_laser_405(self):
        if self.QPushButton_laser_405.isChecked():
            self.Signal_setlaseron_405.emit()
        else:
            self.Signal_setlaseroff_405.emit()

    def set_coordinates(self):
        self.Signal_setcoordinates.emit()

    def reset_coordinates(self):
        self.Signal_resetcoordinates.emit()
        self.QSpinBox_coordinate_x.setValue(1)
        self.QSpinBox_coordinate_y.setValue(1)
        self.QSpinBox_coordinate_n.setValue(1024)
        self.QSpinBox_coordinate_bin.setValue(1)

    def deck_move_up(self):
        self.Signal_deck_up.emit()

    def deck_move_down(self):
        self.Signal_deck_down.emit()

    def deck_move(self):
        self.Signal_deck_move.emit()

    def deck_move_stop(self):
        self.Signal_deck_move_stop.emit()

    def piezo_move(self):
        self.Signal_piezo_move.emit()

    def start_video(self):
        self.Signal_start_video.emit()

    def stop_video(self):
        self.Signal_stop_video.emit()

    def run_ft(self):
        self.Signal_run_fft.emit()

    def stop_ft(self):
        self.Signal_stop_fft.emit()

    def save(self):
        self.Signal_save_file.emit()

    def resolft_2d(self):
        self.Signal_2d_resolft.emit()

    def resolft_3d(self):
        self.Signal_3d_resolft.emit()

    def beadscan_2d(self):
        self.Signal_beadscan_2d.emit()

    def update_trigger_parameter_sets(self):
        cind = self.QComboBox_trigger_parameter.currentIndex()
        if cind == 0:
            self.QDoubleSpinBox_cycle_period.setValue(0.100)
            self.QDoubleSpinBox_piezo_start.setValue(0.050)
            self.QDoubleSpinBox_start_x.setValue(0.000)
            self.QDoubleSpinBox_start_y.setValue(0.000)
            self.QDoubleSpinBox_start_z.setValue(0.000)
            self.QDoubleSpinBox_step_x.setValue(0.040)
            self.QDoubleSpinBox_step_y.setValue(0.040)
            self.QDoubleSpinBox_step_z.setValue(0.040)
            self.QDoubleSpinBox_range_x.setValue(1.000)
            self.QDoubleSpinBox_range_y.setValue(1.000)
            self.QDoubleSpinBox_range_z.setValue(0.600)
            self.QDoubleSpinBox_ttl_start_on_405.setValue(0.005)
            self.QDoubleSpinBox_ttl_stop_on_405.setValue(0.010)
            self.QDoubleSpinBox_ttl_start_off_488_0.setValue(0.012)
            self.QDoubleSpinBox_ttl_stop_off_488_0.setValue(0.017)
            self.QDoubleSpinBox_ttl_start_off_488_1.setValue(0.012)
            self.QDoubleSpinBox_ttl_stop_off_488_1.setValue(0.017)
            self.QDoubleSpinBox_ttl_start_read_488_2.setValue(0.020)
            self.QDoubleSpinBox_ttl_stop_read_488_2.setValue(0.040)
            self.QDoubleSpinBox_ttl_start_camera.setValue(0.020)
            self.QDoubleSpinBox_ttl_stop_camera.setValue(0.040)
        if cind == 1:
            self.QDoubleSpinBox_cycle_period.setValue(0.075)
            self.QDoubleSpinBox_piezo_start.setValue(0.050)
            self.QDoubleSpinBox_start_x.setValue(0.000)
            self.QDoubleSpinBox_start_y.setValue(0.000)
            self.QDoubleSpinBox_start_z.setValue(0.000)
            self.QDoubleSpinBox_step_x.setValue(0.032)
            self.QDoubleSpinBox_step_y.setValue(0.032)
            self.QDoubleSpinBox_step_z.setValue(0.050)
            self.QDoubleSpinBox_range_x.setValue(0.960)
            self.QDoubleSpinBox_range_y.setValue(0.960)
            self.QDoubleSpinBox_range_z.setValue(0.500)
            self.QDoubleSpinBox_ttl_start_on_405.setValue(0.005)
            self.QDoubleSpinBox_ttl_stop_on_405.setValue(0.006)
            self.QDoubleSpinBox_ttl_start_off_488_0.setValue(0.008)
            self.QDoubleSpinBox_ttl_stop_off_488_0.setValue(0.010)
            self.QDoubleSpinBox_ttl_start_off_488_1.setValue(0.008)
            self.QDoubleSpinBox_ttl_stop_off_488_1.setValue(0.010)
            self.QDoubleSpinBox_ttl_start_read_488_2.setValue(0.040)
            self.QDoubleSpinBox_ttl_stop_read_488_2.setValue(0.041)
            self.QDoubleSpinBox_ttl_start_camera.setValue(0.040)
            self.QDoubleSpinBox_ttl_stop_camera.setValue(0.041)


# import sys
#
# if __name__ == "__main__":
#     app = QtWidgets.QApplication(sys.argv)
#     window = ConWidget()
#     window.show()
#     sys.exit(app.exec_())
