from PyQt5 import QtWidgets, QtCore


class AOWidget(QtWidgets.QWidget):
    
    Signal_shwfs_initiate = QtCore.pyqtSignal()
    Signal_shwfs_computewf = QtCore.pyqtSignal()
    Signal_shwfs_correctwf = QtCore.pyqtSignal()
    Signal_shwfs_savewf = QtCore.pyqtSignal()
    Signal_wfs_start = QtCore.pyqtSignal()
    Signal_wfs_stop = QtCore.pyqtSignal()
    Signal_shwfs_run = QtCore.pyqtSignal()
    Signal_shwfs_stop = QtCore.pyqtSignal()
    Signal_push_actuator = QtCore.pyqtSignal()
    Signal_null_dm = QtCore.pyqtSignal()
    Signal_flat_dm = QtCore.pyqtSignal()
    Signal_load_dm = QtCore.pyqtSignal(str)
    Signal_save_dm = QtCore.pyqtSignal()
    Signal_set_zernike = QtCore.pyqtSignal()
    Signal_influence_function = QtCore.pyqtSignal()
    Signal_sensorlessAO_run = QtCore.pyqtSignal()
    Signal_manual_ao = QtCore.pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        
        layout = QtWidgets.QVBoxLayout(self)
        Group_exposuretime = QtWidgets.QGroupBox('SH Camera')
        Group_exposuretime.setStyleSheet("font: bold Arial 10px")
        Group_parameters = QtWidgets.QGroupBox('Parameters')
        Group_parameters.setStyleSheet("font: bold Arial 10px")
        Group_commands = QtWidgets.QGroupBox('Wavefront Sensor')
        Group_commands.setStyleSheet("font: bold Arial 10px")
        Group_deformablemirror = QtWidgets.QGroupBox('Deformable Mirror')
        Group_deformablemirror.setStyleSheet("font: bold Arial 10px")
        Group_sensorlessao = QtWidgets.QGroupBox('Sensorless Ao')
        Group_sensorlessao.setStyleSheet("font: bold Arial 10px")
        Group_File = QtWidgets.QGroupBox('File')
        Group_File.setStyleSheet("font: bold Arial 10px")
        layout.addStretch()
        layout.addWidget(Group_exposuretime)
        layout.addWidget(Group_parameters)
        layout.addWidget(Group_commands)
        layout.addWidget(Group_deformablemirror)
        layout.addWidget(Group_sensorlessao)
        layout.addWidget(Group_File)
        layout.addStretch()
        self.setLayout(layout)
        
        Layout_exposuretime = QtWidgets.QGridLayout()
        self.Label_exposuretime = QtWidgets.QLabel(str('Exposure time'))
        self.Label_exposuretime.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_exposuretime = QtWidgets.QLCDNumber()
        self.lcdNumber_exposuretime.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_exposuretime.setDecMode()
        self.QDoubleSpinBox_exposuretime = QtWidgets.QDoubleSpinBox()
        self.QDoubleSpinBox_exposuretime.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QDoubleSpinBox_exposuretime.setRange(0, 10)
        self.QDoubleSpinBox_exposuretime.setSingleStep(0.005)
        self.QDoubleSpinBox_exposuretime.setDecimals(3)
        self.QDoubleSpinBox_exposuretime.setValue(0.05)
        self.Label_shimgmax = QtWidgets.QLabel(str('SHImage MAX'))
        self.Label_shimgmax.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_shimgmax = QtWidgets.QLCDNumber()
        self.lcdNumber_shimgmax.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_shimgmax.setDecMode()
        self.Label_shimgmin = QtWidgets.QLabel(str('SHImage MIN'))
        self.Label_shimgmin.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_shimgmin = QtWidgets.QLCDNumber()
        self.lcdNumber_shimgmin.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_shimgmin.setDecMode()
        self.Label_wfmax = QtWidgets.QLabel(str('Wavefront MAX'))
        self.Label_wfmax.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_wfmax = QtWidgets.QLCDNumber()
        self.lcdNumber_wfmax.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_wfmax.setDecMode()
        self.Label_wfmin = QtWidgets.QLabel(str('Wavefront MIN'))
        self.Label_wfmin.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_wfmin = QtWidgets.QLCDNumber()
        self.lcdNumber_wfmin.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_wfmin.setDecMode()
        self.Label_wfrms = QtWidgets.QLabel(str('Wavefront RMS'))
        self.Label_wfrms.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_wfrms = QtWidgets.QLCDNumber()
        self.lcdNumber_wfrms.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.lcdNumber_wfrms.setDecMode()
        Layout_exposuretime.addWidget(self.Label_exposuretime, 0, 0, 1, 1)
        Layout_exposuretime.addWidget(self.QDoubleSpinBox_exposuretime, 0, 1, 1, 1)
        Layout_exposuretime.addWidget(self.lcdNumber_exposuretime, 0, 2, 1, 1)
        Layout_exposuretime.addWidget(self.Label_wfmin, 1, 0, 1, 1)
        Layout_exposuretime.addWidget(self.lcdNumber_wfmin, 2, 0, 1, 1)
        Layout_exposuretime.addWidget(self.Label_wfmax, 1, 1, 1, 1)
        Layout_exposuretime.addWidget(self.lcdNumber_wfmax, 2, 1, 1, 1)
        Layout_exposuretime.addWidget(self.Label_wfrms, 1, 2, 1, 1)
        Layout_exposuretime.addWidget(self.lcdNumber_wfrms, 2, 2, 1, 1)
        Group_exposuretime.setLayout(Layout_exposuretime)
        
        Layout_parameters = QtWidgets.QGridLayout()
        self.Label_base = QtWidgets.QLabel(str('Base'))
        self.Label_base.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.Label_base_xcenter = QtWidgets.QLabel(str('X_center'))
        self.Label_base_xcenter.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_base_xcenter = QtWidgets.QSpinBox()
        self.QSpinBox_base_xcenter.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_base_xcenter.setRange(0, 2048)
        self.QSpinBox_base_xcenter.setSingleStep(1)
        self.QSpinBox_base_xcenter.setValue(1024)
        self.Label_base_ycenter = QtWidgets.QLabel(str('Y_center'))
        self.Label_base_ycenter.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_base_ycenter = QtWidgets.QSpinBox()
        self.QSpinBox_base_ycenter.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_base_ycenter.setRange(0, 2048)
        self.QSpinBox_base_ycenter.setSingleStep(1)
        self.QSpinBox_base_ycenter.setValue(1024)
        self.Label_offset = QtWidgets.QLabel(str('Offset'))
        self.Label_offset.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.Label_offset_xcenter = QtWidgets.QLabel(str('X_center'))
        self.Label_offset_xcenter.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_offset_xcenter = QtWidgets.QSpinBox()
        self.QSpinBox_offset_xcenter.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_offset_xcenter.setRange(0, 2048)
        self.QSpinBox_offset_xcenter.setSingleStep(1)
        self.QSpinBox_offset_xcenter.setValue(1024)
        self.Label_offset_ycenter = QtWidgets.QLabel(str('Y_center'))
        self.Label_offset_ycenter.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_offset_ycenter = QtWidgets.QSpinBox()
        self.QSpinBox_offset_ycenter.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_offset_ycenter.setRange(0, 2048)
        self.QSpinBox_offset_ycenter.setSingleStep(1)
        self.QSpinBox_offset_ycenter.setValue(1024)
        self.Label_diamter = QtWidgets.QLabel(str('Diamter'))
        self.Label_diamter.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_diamter = QtWidgets.QSpinBox()
        self.QSpinBox_diamter.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_diamter.setRange(0, 64)
        self.QSpinBox_diamter.setSingleStep(1)
        self.QSpinBox_diamter.setValue(14)
        self.Label_spacing = QtWidgets.QLabel(str('Spacing'))
        self.Label_spacing.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_spacing = QtWidgets.QSpinBox()
        self.QSpinBox_spacing.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_spacing.setRange(0, 64)
        self.QSpinBox_spacing.setSingleStep(1)
        self.QSpinBox_spacing.setValue(26)
        self.Label_radius = QtWidgets.QLabel(str('Radius'))
        self.Label_radius.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_radius = QtWidgets.QSpinBox()
        self.QSpinBox_radius.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_radius.setRange(0, 64)
        self.QSpinBox_radius.setSingleStep(1)
        self.QSpinBox_radius.setValue(12)
        # self.button_shwfs_setparamters = QtWidgets.QPushButton('Set\nParameters', self)
        # self.button_shwfs_setparamters.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        Layout_parameters.addWidget(self.Label_base, 0, 0, 1, 1)
        Layout_parameters.addWidget(self.Label_base_xcenter, 1, 0, 1, 1)
        Layout_parameters.addWidget(self.QSpinBox_base_xcenter, 1, 1, 1, 1)
        Layout_parameters.addWidget(self.Label_base_ycenter, 2, 0, 1, 1)
        Layout_parameters.addWidget(self.QSpinBox_base_ycenter, 2, 1, 1, 1)
        Layout_parameters.addWidget(self.Label_offset, 0, 2, 1, 1)
        Layout_parameters.addWidget(self.Label_offset_xcenter, 1, 2, 1, 1)
        Layout_parameters.addWidget(self.QSpinBox_offset_xcenter, 1, 3, 1, 1)
        Layout_parameters.addWidget(self.Label_offset_ycenter, 2, 2, 1, 1)
        Layout_parameters.addWidget(self.QSpinBox_offset_ycenter, 2, 3, 1, 1)
        Layout_parameters.addWidget(self.Label_diamter, 4, 0, 1, 1)
        Layout_parameters.addWidget(self.QSpinBox_diamter, 5, 0, 1, 1)
        Layout_parameters.addWidget(self.Label_spacing, 4, 1, 1, 1)
        Layout_parameters.addWidget(self.QSpinBox_spacing, 5, 1, 1, 1)
        Layout_parameters.addWidget(self.Label_radius, 4, 2, 1, 1)
        Layout_parameters.addWidget(self.QSpinBox_radius, 5, 2, 1, 1)
        # Layout_parameters.addWidget(self.button_shwfs_setparamters, 4, 3, 2, 1)
        Group_parameters.setLayout(Layout_parameters)

        Layout_commands = QtWidgets.QGridLayout()
        self.button_shwfs_initiate = QtWidgets.QPushButton('Initiate WFS', self)
        self.button_shwfs_initiate.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_wfsstart = QtWidgets.QPushButton('SHStart', self)
        self.button_wfsstart.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_wfsstop = QtWidgets.QPushButton('SHStop', self)
        self.button_wfsstop.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_run_wfr = QtWidgets.QPushButton('RunWF', self)
        self.button_run_wfr.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_stop_wfr = QtWidgets.QPushButton('StopWF', self)
        self.button_stop_wfr.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")        
        self.button_shwfs_computewf = QtWidgets.QPushButton('ComputeWF', self)
        self.button_shwfs_computewf.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_shwfs_correctwf = QtWidgets.QPushButton('CorrectWF', self)
        self.button_shwfs_correctwf.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_shwfs_savewf = QtWidgets.QPushButton('SaveWF', self)
        self.button_shwfs_savewf.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.radioButton_exclude_zm = QtWidgets.QRadioButton("Exclude")
        self.radioButton_exclude_zm.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        Layout_commands.addWidget(self.button_shwfs_initiate, 0, 0, 1, 1)
        Layout_commands.addWidget(self.button_wfsstart, 1, 0, 1, 1)
        Layout_commands.addWidget(self.button_wfsstop, 1, 1, 1, 1)
        Layout_commands.addWidget(self.button_run_wfr, 3, 0, 1, 1)
        Layout_commands.addWidget(self.button_stop_wfr, 3, 1, 1, 1)
        Layout_commands.addWidget(self.radioButton_exclude_zm, 4, 0, 1, 1)
        Layout_commands.addWidget(self.button_shwfs_computewf, 4, 1, 1, 1)
        Layout_commands.addWidget(self.button_shwfs_correctwf, 5, 0, 1, 1)
        Layout_commands.addWidget(self.button_shwfs_savewf, 5, 1, 1, 1)
        Group_commands.setLayout(Layout_commands)
        
        Layout_deformablemirror = QtWidgets.QGridLayout()
        self.Label_actuator = QtWidgets.QLabel(str('Actuator'))
        self.Label_actuator.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_actuator = QtWidgets.QSpinBox()
        self.QSpinBox_actuator.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_actuator.setRange(0, 96)
        self.QSpinBox_actuator.setSingleStep(1)
        self.QSpinBox_actuator.setValue(0)
        self.Label_actuator_push = QtWidgets.QLabel(str('Push'))
        self.Label_actuator_push.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QDoubleSpinBox_actuator_push = QtWidgets.QDoubleSpinBox()
        self.QDoubleSpinBox_actuator_push.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QDoubleSpinBox_actuator_push.setRange(-1, 1)
        self.QDoubleSpinBox_actuator_push.setSingleStep(0.005)
        self.QDoubleSpinBox_actuator_push.setDecimals(3)
        self.QDoubleSpinBox_actuator_push.setValue(0.00)
        self.button_push_actuator = QtWidgets.QPushButton('Push Actuator', self)
        self.button_push_actuator.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.Label_zernike_mode = QtWidgets.QLabel(str('Zernike Mode'))
        self.Label_zernike_mode.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_zernike_mode = QtWidgets.QSpinBox()
        self.QSpinBox_zernike_mode.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_zernike_mode.setRange(0, 100)
        self.QSpinBox_zernike_mode.setSingleStep(1)
        self.QSpinBox_zernike_mode.setValue(0)
        self.Label_zernike_mode_amp = QtWidgets.QLabel(str('Amplitude'))
        self.Label_zernike_mode_amp.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QDoubleSpinBox_zernike_mode_amp = QtWidgets.QDoubleSpinBox()
        self.QDoubleSpinBox_zernike_mode_amp.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QDoubleSpinBox_zernike_mode_amp.setRange(-20, 20)
        self.QDoubleSpinBox_zernike_mode_amp.setSingleStep(0.01)
        self.QDoubleSpinBox_zernike_mode_amp.setDecimals(2)
        self.QDoubleSpinBox_zernike_mode_amp.setValue(0.00)
        self.button_set_zernike_mode = QtWidgets.QPushButton('Set Zernike Mode', self)
        self.button_set_zernike_mode.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_influence_fuction_laser = QtWidgets.QPushButton('Influence Function', self)
        self.button_influence_fuction_laser.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_nullDM = QtWidgets.QPushButton('Null DM', self)
        self.button_nullDM.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_flatDM = QtWidgets.QPushButton('Flat DM', self)
        self.button_flatDM.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_loadDM = QtWidgets.QPushButton('Load DM', self)
        self.button_loadDM.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_manual_ao = QtWidgets.QPushButton('Manual AO', self)
        self.button_manual_ao.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        Layout_deformablemirror.addWidget(self.Label_actuator, 0, 0, 1, 1)
        Layout_deformablemirror.addWidget(self.QSpinBox_actuator, 0, 1, 1, 1)
        Layout_deformablemirror.addWidget(self.Label_actuator_push, 1, 0, 1, 1)
        Layout_deformablemirror.addWidget(self.QDoubleSpinBox_actuator_push, 1, 1, 1, 1)
        Layout_deformablemirror.addWidget(self.button_push_actuator, 2, 0, 1, 2)
        Layout_deformablemirror.addWidget(self.Label_zernike_mode, 0, 2, 1, 1)
        Layout_deformablemirror.addWidget(self.QSpinBox_zernike_mode, 0, 3, 1, 1)
        Layout_deformablemirror.addWidget(self.Label_zernike_mode_amp, 1, 2, 1, 1)
        Layout_deformablemirror.addWidget(self.QDoubleSpinBox_zernike_mode_amp, 1, 3, 1, 1)
        Layout_deformablemirror.addWidget(self.button_set_zernike_mode, 2, 2, 1, 2)
        Layout_deformablemirror.addWidget(self.button_influence_fuction_laser, 3, 0, 1, 2)
        Layout_deformablemirror.addWidget(self.button_nullDM, 3, 2, 1, 1)
        Layout_deformablemirror.addWidget(self.button_flatDM, 3, 3, 1, 1)
        Layout_deformablemirror.addWidget(self.button_loadDM, 4, 0, 1, 1)
        Layout_deformablemirror.addWidget(self.button_manual_ao, 4, 3, 1, 1)
        Group_deformablemirror.setLayout(Layout_deformablemirror)
        
        Layout_sensorlessao = QtWidgets.QGridLayout()
        self.Label_zernike_modes = QtWidgets.QLabel(str('Zernike Modes'))
        self.Label_zernike_modes.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.Label_zernike_mode_start = QtWidgets.QLabel(str('From'))
        self.Label_zernike_mode_start.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_zernike_mode_start = QtWidgets.QSpinBox()
        self.QSpinBox_zernike_mode_start.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_zernike_mode_start.setRange(0, 96)
        self.QSpinBox_zernike_mode_start.setSingleStep(1)
        self.QSpinBox_zernike_mode_start.setValue(4)
        self.Label_zernike_mode_stop = QtWidgets.QLabel(str('To'))
        self.Label_zernike_mode_stop.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_zernike_mode_stop = QtWidgets.QSpinBox()
        self.QSpinBox_zernike_mode_stop.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_zernike_mode_stop.setRange(0, 96)
        self.QSpinBox_zernike_mode_stop.setSingleStep(1)
        self.QSpinBox_zernike_mode_stop.setValue(22)
        self.Label_zernike_modes_amps = QtWidgets.QLabel(str('Amplitudes'))
        self.Label_zernike_modes_amps.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.Label_zernike_modes_amps_start = QtWidgets.QLabel(str('From'))
        self.Label_zernike_modes_amps_start.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QDoubleSpinBox_zernike_mode_amps_start = QtWidgets.QDoubleSpinBox()
        self.QDoubleSpinBox_zernike_mode_amps_start.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QDoubleSpinBox_zernike_mode_amps_start.setRange(-50, 50)
        self.QDoubleSpinBox_zernike_mode_amps_start.setSingleStep(0.01)
        self.QDoubleSpinBox_zernike_mode_amps_start.setDecimals(2)
        self.QDoubleSpinBox_zernike_mode_amps_start.setValue(-1.6)
        self.Label_zernike_modes_amps_stepnum = QtWidgets.QLabel(str('StepNum'))
        self.Label_zernike_modes_amps_stepnum.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QSpinBox_zernike_mode_amps_stepnum = QtWidgets.QSpinBox()
        self.QSpinBox_zernike_mode_amps_stepnum.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QSpinBox_zernike_mode_amps_stepnum.setRange(0, 50)
        self.QSpinBox_zernike_mode_amps_stepnum.setSingleStep(2)
        self.QSpinBox_zernike_mode_amps_stepnum.setValue(5)
        self.Label_zernike_modes_amps_step = QtWidgets.QLabel(str('StepSize'))
        self.Label_zernike_modes_amps_step.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QDoubleSpinBox_zernike_mode_amps_step = QtWidgets.QDoubleSpinBox()
        self.QDoubleSpinBox_zernike_mode_amps_step.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QDoubleSpinBox_zernike_mode_amps_step.setRange(0, 50)
        self.QDoubleSpinBox_zernike_mode_amps_step.setSingleStep(0.01)
        self.QDoubleSpinBox_zernike_mode_amps_step.setDecimals(2)
        self.QDoubleSpinBox_zernike_mode_amps_step.setValue(0.8)
        self.Label_lpf = QtWidgets.QLabel(str('LPF'))
        self.Label_lpf.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QDoubleSpinBox_lpf = QtWidgets.QDoubleSpinBox()
        self.QDoubleSpinBox_lpf.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QDoubleSpinBox_lpf.setRange(0, 1)
        self.QDoubleSpinBox_lpf.setSingleStep(0.05)
        self.QDoubleSpinBox_lpf.setDecimals(2)
        self.QDoubleSpinBox_lpf.setValue(0.08)
        self.Label_hpf = QtWidgets.QLabel(str('HPF'))
        self.Label_hpf.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QDoubleSpinBox_hpf = QtWidgets.QDoubleSpinBox()
        self.QDoubleSpinBox_hpf.setStyleSheet("background-color: dark; color: black; font: bold Arial 10px")
        self.QDoubleSpinBox_hpf.setRange(0, 1)
        self.QDoubleSpinBox_hpf.setSingleStep(0.005)
        self.QDoubleSpinBox_hpf.setDecimals(2)
        self.QDoubleSpinBox_hpf.setValue(0.64)
        self.Label_metric_function = QtWidgets.QLabel(str('Image Metric'))
        self.Label_metric_function.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QComboBox_metric = QtWidgets.QComboBox()
        self.QComboBox_metric.addItem("SNR (FFT)")
        self.QComboBox_metric.addItem("Max (Intensity)")
        self.QComboBox_metric.addItem("HighPass (FFT)")
        self.QComboBox_metric.setStyleSheet("background-color: lightgrey; color: black; font: bold Arial 10px")
        self.button_sensorlessAO_run = QtWidgets.QPushButton('Run AO', self)
        self.button_sensorlessAO_run.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
        self.button_saveDM = QtWidgets.QPushButton('Save DM', self)
        self.button_saveDM.setStyleSheet("background-color: lightgrey; color: dark; font: bold Arial 10px")
       
        Layout_sensorlessao.addWidget(self.Label_zernike_modes, 0, 0, 1, 2)
        Layout_sensorlessao.addWidget(self.Label_zernike_mode_start, 1, 0, 1, 1)
        Layout_sensorlessao.addWidget(self.QSpinBox_zernike_mode_start, 1, 1, 1, 1)
        Layout_sensorlessao.addWidget(self.Label_zernike_mode_stop, 2, 0, 1, 1)
        Layout_sensorlessao.addWidget(self.QSpinBox_zernike_mode_stop, 2, 1, 1, 1)
        Layout_sensorlessao.addWidget(self.Label_zernike_modes_amps, 0, 2, 1, 2 )
        Layout_sensorlessao.addWidget(self.Label_zernike_modes_amps_start, 1, 2, 1, 1)
        Layout_sensorlessao.addWidget(self.QDoubleSpinBox_zernike_mode_amps_start, 1, 3, 1, 1)
        Layout_sensorlessao.addWidget(self.Label_zernike_modes_amps_stepnum, 2, 2, 1, 1)
        Layout_sensorlessao.addWidget(self.QSpinBox_zernike_mode_amps_stepnum, 2, 3, 1, 1)
        Layout_sensorlessao.addWidget(self.Label_zernike_modes_amps_step, 3, 2, 1, 1)
        Layout_sensorlessao.addWidget(self.QDoubleSpinBox_zernike_mode_amps_step, 3, 3, 1, 1)
        Layout_sensorlessao.addWidget(self.Label_lpf, 0, 4, 1, 1)
        Layout_sensorlessao.addWidget(self.QDoubleSpinBox_lpf, 1, 4, 1, 1)
        Layout_sensorlessao.addWidget(self.Label_hpf, 2, 4, 1, 1)
        Layout_sensorlessao.addWidget(self.QDoubleSpinBox_hpf, 3, 4, 1, 1)
        Layout_sensorlessao.addWidget(self.Label_metric_function, 0, 5, 1, 1)
        Layout_sensorlessao.addWidget(self.QComboBox_metric, 1, 5, 1, 1)
        Layout_sensorlessao.addWidget(self.button_sensorlessAO_run, 2, 5, 1, 1)
        Layout_sensorlessao.addWidget(self.button_saveDM, 3, 5, 1, 1)
        Group_sensorlessao.setLayout(Layout_sensorlessao)
        
        Layout_File = QtWidgets.QGridLayout()
        self.QLabel_file_name = QtWidgets.QLabel(str('File name'))
        self.QLabel_file_name.setStyleSheet("background-color: dark; color: white; font: bold Arial 10px")
        self.QLineEdit_filename = QtWidgets.QLineEdit()
        self.QLineEdit_filename.setStyleSheet("background-color: dark; font: bold Arial 10px")
        Layout_File.addWidget(self.QLabel_file_name, 0, 0, 1, 1)
        Layout_File.addWidget(self.QLineEdit_filename, 0, 1, 1, 5)
        Group_File.setLayout(Layout_File)

        self.button_wfsstart.clicked.connect(self.Signal_wfs_start.emit)
        self.button_wfsstop.clicked.connect(self.Signal_wfs_stop.emit)
        self.button_shwfs_initiate.clicked.connect(self.Signal_shwfs_initiate.emit)
        self.button_shwfs_computewf.clicked.connect(self.Signal_shwfs_computewf.emit)
        self.button_shwfs_correctwf.clicked.connect(self.Signal_shwfs_correctwf.emit)
        self.button_shwfs_savewf.clicked.connect(self.Signal_shwfs_savewf.emit)
        self.button_push_actuator.clicked.connect(self.Signal_push_actuator.emit)
        self.button_set_zernike_mode.clicked.connect(self.Signal_set_zernike.emit)
        self.button_nullDM.clicked.connect(self.Signal_null_dm.emit)
        self.button_flatDM.clicked.connect(self.Signal_flat_dm.emit)
        self.button_run_wfr.clicked.connect(self.Signal_shwfs_run.emit)
        self.button_stop_wfr.clicked.connect(self.Signal_shwfs_stop.emit)
        self.button_influence_fuction_laser.clicked.connect(self.Signal_influence_function.emit)
        self.button_sensorlessAO_run.clicked.connect(self.Signal_sensorlessAO_run.emit)
        self.button_manual_ao.clicked.connect(self.Signal_manual_ao.emit)
        self.button_loadDM.clicked.connect(self.dialog)
        self.button_saveDM.clicked.connect(self.Signal_save_dm.emit)

        self.QSpinBox_base_xcenter.setValue(465)
        self.QSpinBox_base_ycenter.setValue(637)
        self.QSpinBox_offset_xcenter.setValue(465)
        self.QSpinBox_offset_ycenter.setValue(637)
        self.QSpinBox_diamter.setValue(19)
        self.QSpinBox_spacing.setValue(33)
        self.QSpinBox_radius.setValue(14)
        
    def dialog(self):
        file, check = QtWidgets.QFileDialog.getOpenFileName(None, "QtWidgets.QFileDialog.getOpenFileName()","", "All Files (*);;Python Files (*.py);;Text Files (*.txt)")
        if check:
            print(file)
            self.Signal_load_dm.emit(file)
