from PyQt5 import QtWidgets, QtCore

from utilities import customized_widgets as cw


class ConWidget(QtWidgets.QWidget):
    Signal_check_emccd_temperature = QtCore.pyqtSignal()
    Signal_switch_emccd_cooler_on = QtCore.pyqtSignal()
    Signal_switch_emccd_cooler_off = QtCore.pyqtSignal()
    Signal_piezo_move_x = QtCore.pyqtSignal()
    Signal_piezo_move_y = QtCore.pyqtSignal()
    Signal_piezo_move_z = QtCore.pyqtSignal()
    Signal_deck_up = QtCore.pyqtSignal()
    Signal_deck_down = QtCore.pyqtSignal()
    Signal_deck_move = QtCore.pyqtSignal()
    Signal_deck_move_stop = QtCore.pyqtSignal()
    Signal_galvo_set = QtCore.pyqtSignal()
    Signal_galvo_reset = QtCore.pyqtSignal()
    Signal_setcoordinates = QtCore.pyqtSignal()
    Signal_resetcoordinates = QtCore.pyqtSignal()
    Signal_setbin = QtCore.pyqtSignal()
    Signal_setlaseron_488_0 = QtCore.pyqtSignal()
    Signal_setlaseron_488_1 = QtCore.pyqtSignal()
    Signal_setlaseron_488_2 = QtCore.pyqtSignal()
    Signal_setlaseron_405 = QtCore.pyqtSignal()
    Signal_setlaseroff_488_0 = QtCore.pyqtSignal()
    Signal_setlaseroff_488_1 = QtCore.pyqtSignal()
    Signal_setlaseroff_488_2 = QtCore.pyqtSignal()
    Signal_setlaseroff_405 = QtCore.pyqtSignal()
    Signal_plot_trigger = QtCore.pyqtSignal()
    Signal_start_video = QtCore.pyqtSignal()
    Signal_stop_video = QtCore.pyqtSignal()
    Signal_run_fft = QtCore.pyqtSignal()
    Signal_stop_fft = QtCore.pyqtSignal()
    Signal_run_plot_profile = QtCore.pyqtSignal()
    Signal_stop_plot_profile = QtCore.pyqtSignal()
    Signal_2d_resolft = QtCore.pyqtSignal()
    # Signal_3d_resolft = QtCore.pyqtSignal()
    Signal_beadscan_2d = QtCore.pyqtSignal()
    # Signal_beadscan_3d = QtCore.pyqtSignal()
    Signal_galvo_scan = QtCore.pyqtSignal()
    Signal_save_file = QtCore.pyqtSignal(str)

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        layout = QtWidgets.QVBoxLayout()
        dock_Camera, group_Camera = cw.create_dock('Camera')
        dock_Position, group_Position = cw.create_dock('Position')
        dock_Illumination, group_Illumination = cw.create_dock('Laser')
        dock_Triggers, group_Triggers = cw.create_dock('Triggers')
        dock_DataAquisition, group_DataAquisition = cw.create_dock('Image Acquisition')
        layout.addWidget(dock_Camera)
        layout.addWidget(dock_Position)
        layout.addWidget(dock_Illumination)
        layout.addWidget(dock_Triggers)
        layout.addWidget(dock_DataAquisition)
        self.setLayout(layout)

        Layout_Camera = QtWidgets.QHBoxLayout()
        self.QLabel_emccd = cw.label_widget(str('EMCCD'))
        self.QLabel_ccd_tempetature = cw.label_widget(str('CCD Temperature'))
        self.QLCDNumber_ccd_tempetature = cw.lcdnumber_widget(0, 3)
        self.QPushButton_emccd_cooler_check = cw.pushbutton_widget('Check', False, True)
        self.QPushButton_emccd_cooler_switch = cw.pushbutton_widget('OFF', True, True)
        self.QLabel_emccd_exposure_time = cw.label_widget(str('Exposure Time (s)'))
        self.QDoubleSpinBox_emccd_exposure_time = cw.doublespinbox_widget(0, 10, 0.005, 3, 0.02)
        self.QLabel_emccd_gain = cw.label_widget(str('EMCCD Gain'))
        self.QSpinBox_emccd_gain = cw.spinbox_widget(0, 300, 1, 0)
        self.QLabel_emccd_coordinate_x = cw.label_widget(str('X'))
        self.QSpinBox_emccd_coordinate_x = cw.spinbox_widget(0, 2048, 1, 1)
        self.QLabel_emccd_coordinate_y = cw.label_widget(str('Y'))
        self.QSpinBox_emccd_coordinate_y = cw.spinbox_widget(0, 2048, 1, 1)
        self.QLabel_emccd_coordinate_n = cw.label_widget(str('N'))
        self.QSpinBox_emccd_coordinate_n = cw.spinbox_widget(0, 2048, 1, 1024)
        self.QLabel_emccd_coordinate_bin = cw.label_widget(str('Bin'))
        self.QSpinBox_emccd_coordinate_bin = cw.spinbox_widget(0, 1024, 1, 1)
        self.emccd_scroll_area, emccd_scroll_layout = cw.create_scroll_area()
        emccd_scroll_layout.addRow(self.QLabel_emccd)
        emccd_scroll_layout.addRow(self.QLabel_ccd_tempetature, self.QLCDNumber_ccd_tempetature)
        emccd_scroll_layout.addRow(self.QPushButton_emccd_cooler_check, self.QPushButton_emccd_cooler_switch)
        emccd_scroll_layout.addRow(self.QLabel_emccd_exposure_time, self.QDoubleSpinBox_emccd_exposure_time)
        emccd_scroll_layout.addRow(self.QLabel_emccd_gain, self.QSpinBox_emccd_gain)
        emccd_scroll_layout.addRow(self.QLabel_emccd_coordinate_x, self.QSpinBox_emccd_coordinate_x)
        emccd_scroll_layout.addRow(self.QLabel_emccd_coordinate_y, self.QSpinBox_emccd_coordinate_y)
        emccd_scroll_layout.addRow(self.QLabel_emccd_coordinate_n, self.QSpinBox_emccd_coordinate_n)
        emccd_scroll_layout.addRow(self.QLabel_emccd_coordinate_bin, self.QSpinBox_emccd_coordinate_bin)
        self.QLabel_scmos = cw.label_widget(str('sCMOS'))
        self.QLabel_scmos_exposure_time = cw.label_widget(str('Exposure time (s)'))
        self.QDoubleSpinBox_scmos_exposure_time = cw.doublespinbox_widget(0, 10, 0.005, 3, 0.01)
        self.scmos_scroll_area, scmos_scroll_layout = cw.create_scroll_area()
        scmos_scroll_layout.addRow(self.QLabel_scmos)
        scmos_scroll_layout.addRow(self.QLabel_scmos_exposure_time, self.QDoubleSpinBox_scmos_exposure_time)
        Layout_Camera.addWidget(self.emccd_scroll_area)
        Layout_Camera.addWidget(self.scmos_scroll_area)
        group_Camera.setLayout(Layout_Camera)

        Layout_Position = QtWidgets.QHBoxLayout()
        self.QLabel_mad_deck = cw.label_widget(str('Mad Deck'))
        self.QLabel_deck_position = cw.label_widget(str('Position (mm)'))
        self.QLCDNumber_deck_position = cw.lcdnumber_widget()
        self.QLabel_deck_move_fine = cw.label_widget(str('Single step'))
        self.QPushButton_move_deck_up = cw.pushbutton_widget('Up')
        self.QPushButton_move_deck_down = cw.pushbutton_widget('Down')
        self.QLabel_deck_movement = cw.label_widget(str('Distance (mm)'))
        self.QDoubleSpinBox_deck_movement = cw.doublespinbox_widget(-11.5, 11.5, 0.001, 3, 0.01)
        self.QLabel_deck_velocity = cw.label_widget(str('Velocity (mm)'))
        self.QDoubleSpinBox_deck_velocity = cw.doublespinbox_widget(0.02, 1.50, 0.02, 2, 0.02)
        self.QPushButton_move_deck = cw.pushbutton_widget('Move', checkable=True)
        self.mad_deck_scroll_area, mad_deck_scroll_layout = cw.create_scroll_area()
        mad_deck_scroll_layout.addRow(self.QLabel_mad_deck)
        mad_deck_scroll_layout.addRow(self.QLabel_deck_position, self.QLCDNumber_deck_position)
        mad_deck_scroll_layout.addRow(self.QLabel_deck_movement, self.QDoubleSpinBox_deck_movement)
        mad_deck_scroll_layout.addRow(self.QPushButton_move_deck)
        mad_deck_scroll_layout.addRow(self.QLabel_deck_move_fine)
        mad_deck_scroll_layout.addRow(self.QPushButton_move_deck_up, self.QPushButton_move_deck_down)
        self.QLabel_mcl_stage = cw.label_widget(str('MCL Piezo'))
        self.QLabel_stage_x = cw.label_widget(str('X (um)'))
        self.QDoubleSpinBox_stage_x = cw.doublespinbox_widget(0, 50, 0.02, 2, 0.00)
        self.QLCDNumber_piezo_position_x = cw.lcdnumber_widget()
        self.QLabel_stage_y = cw.label_widget(str('Y (um)'))
        self.QDoubleSpinBox_stage_y = cw.doublespinbox_widget(0, 50, 0.02, 2, 0.00)
        self.QLCDNumber_piezo_position_y = cw.lcdnumber_widget()
        self.QLabel_stage_z = cw.label_widget(str('Z (um)'))
        self.QDoubleSpinBox_stage_z = cw.doublespinbox_widget(0, 50, 0.02, 2, 0.00)
        self.QLCDNumber_piezo_position_z = cw.lcdnumber_widget()
        self.mcl_piezo_scroll_area, mcl_piezo_scroll_layout = cw.create_scroll_area()
        mcl_piezo_scroll_layout.addRow(self.QLabel_mcl_stage)
        mcl_piezo_scroll_layout.addRow(self.QLabel_stage_x, self.QDoubleSpinBox_stage_x)
        mcl_piezo_scroll_layout.addRow(self.QLCDNumber_piezo_position_x)
        mcl_piezo_scroll_layout.addRow(self.QLabel_stage_y, self.QDoubleSpinBox_stage_y)
        mcl_piezo_scroll_layout.addRow(self.QLCDNumber_piezo_position_y)
        mcl_piezo_scroll_layout.addRow(self.QLabel_stage_z, self.QDoubleSpinBox_stage_z)
        mcl_piezo_scroll_layout.addRow(self.QLCDNumber_piezo_position_z)
        self.QLabel_galvo = cw.label_widget(str('Galvo Scanner'))
        self.QLabel_galvo_x = cw.label_widget(str('X / v'))
        self.QDoubleSpinBox_galvo_x = cw.doublespinbox_widget(-10, 10, 0.001, 3, 0)
        self.QLabel_galvo_y = cw.label_widget(str('Y / v'))
        self.QDoubleSpinBox_galvo_y = cw.doublespinbox_widget(-10, 10, 0.001, 3, 0)
        self.galvo_scroll_area, galvo_scroll_layout = cw.create_scroll_area()
        galvo_scroll_layout.addRow(self.QLabel_galvo)
        galvo_scroll_layout.addRow(self.QLabel_galvo_x, self.QDoubleSpinBox_galvo_x)
        galvo_scroll_layout.addRow(self.QLabel_galvo_y, self.QDoubleSpinBox_galvo_y)
        Layout_Position.addWidget(self.mad_deck_scroll_area)
        Layout_Position.addWidget(self.mcl_piezo_scroll_area)
        Layout_Position.addWidget(self.galvo_scroll_area)
        group_Position.setLayout(Layout_Position)

        Layout_Illumination = QtWidgets.QHBoxLayout()
        self.QRadioButton_laser_405 = cw.radiobutton_widget('405 nm')
        self.QDoubleSpinBox_laserpower_405 = cw.doublespinbox_widget(0, 200, 0.1, 1, 0.0)
        self.QPushButton_laser_405 = cw.pushbutton_widget('ON', checkable=True)
        self.QRadioButton_laser_488_0 = cw.radiobutton_widget('488 nm #0')
        self.QDoubleSpinBox_laserpower_488_0 = cw.doublespinbox_widget(0, 200, 0.1, 1, 0.0)
        self.QPushButton_laser_488_0 = cw.pushbutton_widget('ON', checkable=True)
        self.QRadioButton_laser_488_1 = cw.radiobutton_widget('488 nm #1')
        self.QDoubleSpinBox_laserpower_488_1 = cw.doublespinbox_widget(0, 200, 0.1, 1, 0.0)
        self.QPushButton_laser_488_1 = cw.pushbutton_widget('ON', checkable=True)
        self.QRadioButton_laser_488_2 = cw.radiobutton_widget('488 nm #2')
        self.QDoubleSpinBox_laserpower_488_2 = cw.doublespinbox_widget(0, 200, 0.1, 1, 0.0)
        self.QPushButton_laser_488_2 = cw.pushbutton_widget('ON', checkable=True)
        self.laser_405_scroll_area, laser_405_scroll_layout = cw.create_scroll_area()
        self.laser_488_0_scroll_area, laser_488_0_scroll_layout = cw.create_scroll_area()
        self.laser_488_1_scroll_area, laser_488_1_scroll_layout = cw.create_scroll_area()
        self.laser_488_2_scroll_area, laser_488_2_scroll_layout = cw.create_scroll_area()
        laser_405_scroll_layout.addRow(self.QRadioButton_laser_405)
        laser_405_scroll_layout.addRow(self.QDoubleSpinBox_laserpower_405)
        laser_405_scroll_layout.addRow(self.QPushButton_laser_405)
        laser_488_0_scroll_layout.addRow(self.QRadioButton_laser_488_0)
        laser_488_0_scroll_layout.addRow(self.QDoubleSpinBox_laserpower_488_0)
        laser_488_0_scroll_layout.addRow(self.QPushButton_laser_488_0)
        laser_488_1_scroll_layout.addRow(self.QRadioButton_laser_488_1)
        laser_488_1_scroll_layout.addRow(self.QDoubleSpinBox_laserpower_488_1)
        laser_488_1_scroll_layout.addRow(self.QPushButton_laser_488_1)
        laser_488_2_scroll_layout.addRow(self.QRadioButton_laser_488_2)
        laser_488_2_scroll_layout.addRow(self.QDoubleSpinBox_laserpower_488_2)
        laser_488_2_scroll_layout.addRow(self.QPushButton_laser_488_2)
        Layout_Illumination.addWidget(self.laser_405_scroll_area)
        Layout_Illumination.addWidget(self.laser_488_0_scroll_area)
        Layout_Illumination.addWidget(self.laser_488_1_scroll_area)
        Layout_Illumination.addWidget(self.laser_488_2_scroll_area)
        group_Illumination.setLayout(Layout_Illumination)

        Layout_Triggers = QtWidgets.QGridLayout()
        self.QPushButton_plot_trigger = cw.pushbutton_widget('Plot Triggers')
        self.QLabel_cycle_period = cw.label_widget(str('Cycle / s'))
        self.QDoubleSpinBox_cycle_period = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.04)
        self.QLabel_piezo_start = cw.label_widget(str('Piezo_start / s'))
        self.QDoubleSpinBox_piezo_start = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.03)
        self.QLabel_start_positions = cw.label_widget(str('Start / um'))
        self.QLabel_step_sizes = cw.label_widget(str('Step / um'))
        self.QLabel_scan_ranges = cw.label_widget(str('Range / um'))
        self.QLabel_axis_piezo = cw.label_widget(str('Piezo'))
        self.QLabel_axis_x = cw.label_widget(str('X'))
        self.QLabel_axis_y = cw.label_widget(str('Y'))
        self.QLabel_axis_z = cw.label_widget(str('Z'))
        self.QDoubleSpinBox_start_x = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.000)
        self.QDoubleSpinBox_start_y = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.000)
        self.QDoubleSpinBox_start_z = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.000)
        self.QDoubleSpinBox_step_x = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.030)
        self.QDoubleSpinBox_step_y = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.030)
        self.QDoubleSpinBox_step_z = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.080)
        self.QDoubleSpinBox_range_x = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.600)
        self.QDoubleSpinBox_range_y = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.600)
        self.QDoubleSpinBox_range_z = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.800)
        self.QLabel_axis_galvo = cw.label_widget(str('Galvo Scan'))
        self.QLabel_galvo_start_positions = cw.label_widget(str('From / V'))
        self.QLabel_galvo_stop_positions = cw.label_widget(str('To / V'))
        self.QLabel_galvo_step_sizes = cw.label_widget(str('Step / V'))
        self.QLabel_galvo_scan_x = cw.label_widget(str('X'))
        self.QLabel_galvo_scan_y = cw.label_widget(str('Y'))
        self.QDoubleSpinBox_galvo_start_x = cw.doublespinbox_widget(-10, 10, 0.001, 3, -1.0)
        self.QDoubleSpinBox_galvo_start_y = cw.doublespinbox_widget(-10, 10, 0.001, 3, -1.0)
        self.QDoubleSpinBox_galvo_step_x = cw.doublespinbox_widget(-10, 10, 0.001, 3, 0.04)
        self.QDoubleSpinBox_galvo_step_y = cw.doublespinbox_widget(-10, 10, 0.001, 3, 0.04)
        self.QDoubleSpinBox_galvo_stop_x = cw.doublespinbox_widget(-10, 10, 0.001, 3, 1.0)
        self.QDoubleSpinBox_galvo_stop_y = cw.doublespinbox_widget(-10, 10, 0.001, 3, 1.0)
        self.QLabel_ttl = cw.label_widget(str('Lasers'))
        self.QLabel_ttl_starts = cw.label_widget(str('From / s'))
        self.QLabel_ttl_stops = cw.label_widget(str('To / s'))
        self.QLabel_ttl_on_405 = cw.label_widget(str('On 405'))
        self.QLabel_ttl_off_488_0 = cw.label_widget(str('Off 488_1'))
        self.QLabel_ttl_off_488_1 = cw.label_widget(str('Off 488_2'))
        self.QLabel_ttl_read_488_2 = cw.label_widget(str('Img 488'))
        self.QDoubleSpinBox_ttl_start_on_405 = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.002)
        self.QDoubleSpinBox_ttl_start_off_488_0 = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.007)
        self.QDoubleSpinBox_ttl_start_off_488_1 = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.07)
        self.QDoubleSpinBox_ttl_start_read_488_2 = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.012)
        self.QDoubleSpinBox_ttl_stop_on_405 = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.004)
        self.QDoubleSpinBox_ttl_stop_off_488_0 = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.01)
        self.QDoubleSpinBox_ttl_stop_off_488_1 = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.01)
        self.QDoubleSpinBox_ttl_stop_read_488_2 = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.015)
        self.QLabel_ttl_camera = cw.label_widget(str('Camera'))
        self.QLabel_ttl_camera_main = cw.label_widget(str('EMCCD'))
        self.QLabel_ttl_camera_wfs = cw.label_widget(str('sCMOS'))
        self.QLabel_ttl_camera_dm = cw.label_widget(str('DMK33U'))
        self.QLabel_ttl_camera_start = cw.label_widget(str('From / s'))
        self.QLabel_ttl_camera_stop = cw.label_widget(str('To / s'))
        self.QDoubleSpinBox_ttl_start_camera_main = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.012)
        self.QDoubleSpinBox_ttl_start_camera_wfs = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.000)
        self.QDoubleSpinBox_ttl_start_camera_dm = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.000)
        self.QDoubleSpinBox_ttl_stop_camera_main = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.015)
        self.QDoubleSpinBox_ttl_stop_camera_wfs = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.000)
        self.QDoubleSpinBox_ttl_stop_camera_dm = cw.doublespinbox_widget(0, 50, 0.001, 3, 0.000)
        self.QLabel_trigger_parameter = cw.label_widget(str('Pre-sets'))
        self.QComboBox_trigger_parameter = cw.combobox_widget(list_items=['Default', 'Live', 'WFS', 'DM',
                                                                          'UseDefined_1', 'UseDefined_2'])
        self.QLabel_camera_selection = cw.label_widget(str('Camera'))
        self.QComboBox_camera_selection = cw.combobox_widget(list_items=['Main', 'WFS', 'DM'])
        Layout_Triggers.addWidget(self.QLabel_cycle_period, 0, 0, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_cycle_period, 0, 1, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_piezo_start, 1, 0, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_piezo_start, 1, 1, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_start_positions, 3, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_step_sizes, 4, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_scan_ranges, 5, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_axis_piezo, 2, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_axis_x, 2, 1, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_axis_y, 2, 2, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_axis_z, 2, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_start_x, 3, 1, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_start_y, 3, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_start_z, 3, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_step_x, 4, 1, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_step_y, 4, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_step_z, 4, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_range_x, 5, 1, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_range_y, 5, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_range_z, 5, 3, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_axis_galvo, 2, 5, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_galvo_start_positions, 3, 5, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_galvo_stop_positions, 4, 5, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_galvo_step_sizes, 5, 5, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_galvo_scan_x, 2, 6, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_galvo_start_x, 3, 6, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_galvo_stop_x, 4, 6, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_galvo_step_x, 5, 6, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_galvo_scan_y, 2, 7, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_galvo_start_y, 3, 7, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_galvo_stop_y, 4, 7, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_galvo_step_y, 5, 7, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl, 6, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_starts, 7, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_stops, 8, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_on_405, 6, 1, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_off_488_0, 6, 2, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_off_488_1, 6, 3, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_read_488_2, 6, 4, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_on_405, 7, 1, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_off_488_0, 7, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_off_488_1, 7, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_read_488_2, 7, 4, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_on_405, 8, 1, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_off_488_0, 8, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_off_488_1, 8, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_read_488_2, 8, 4, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_camera, 9, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_camera_start, 10, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_camera_stop, 11, 0, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_camera_main, 9, 1, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_camera_wfs, 9, 2, 1, 1)
        Layout_Triggers.addWidget(self.QLabel_ttl_camera_dm, 9, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_camera_main, 10, 1, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_camera_wfs, 10, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_start_camera_dm, 10, 3, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_camera_main, 11, 1, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_camera_wfs, 11, 2, 1, 1)
        Layout_Triggers.addWidget(self.QDoubleSpinBox_ttl_stop_camera_dm, 11, 3, 1, 1)
        Layout_Triggers.addWidget(self.QPushButton_plot_trigger, 0, 6, 1, 2)
        Layout_Triggers.addWidget(self.QLabel_trigger_parameter, 8, 5, 1, 2)
        Layout_Triggers.addWidget(self.QComboBox_trigger_parameter, 9, 5, 1, 2)
        Layout_Triggers.addWidget(self.QLabel_camera_selection, 10, 5, 1, 2)
        Layout_Triggers.addWidget(self.QComboBox_camera_selection, 11, 5, 1, 2)
        group_Triggers.setLayout(Layout_Triggers)

        Layout_DataAquisition = QtWidgets.QGridLayout()
        self.QPushButton_video = cw.pushbutton_widget('Video', checkable=True)
        self.QPushButton_fft = cw.pushbutton_widget('FFT', checkable=True, enable=False)
        self.QPushButton_2d_resolft = cw.pushbutton_widget('2D RESOLFT', enable=False)
        # self.QPushButton_3d_resolft = cw.pushbutton_widget('3D RESOLFT', enable=False)
        self.QPushButton_2d_beadscan = cw.pushbutton_widget('2D BeadScan', enable=False)
        self.QPushButton_3d_beadscan = cw.pushbutton_widget('3D BeadScan', enable=False)
        self.QPushButton_galvo_scan = cw.pushbutton_widget('Galvo Scan', enable=False)
        self.QComboBox_profile_axis = cw.combobox_widget(list_items=['X', 'Y'])
        self.QPushButton_plot_profile = cw.pushbutton_widget('Plot Profile', checkable=True, enable=False)
        self.QPushButton_save = cw.pushbutton_widget('Save')
        Layout_DataAquisition.addWidget(self.QPushButton_video, 0, 0, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_fft, 0, 1, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_2d_resolft, 0, 2, 1, 1)
        # Layout_DataAquisition.addWidget(self.QPushButton_3d_resolft, 0, 3, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_2d_beadscan, 0, 3, 1, 1)
        # Layout_DataAquisition.addWidget(self.QPushButton_3d_beadscan, 1, 3, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_galvo_scan, 1, 2, 1, 1)
        Layout_DataAquisition.addWidget(self.QComboBox_profile_axis, 1, 0, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_plot_profile, 1, 1, 1, 1)
        Layout_DataAquisition.addWidget(self.QPushButton_save, 1, 3, 1, 1)
        group_DataAquisition.setLayout(Layout_DataAquisition)

        self.QPushButton_emccd_cooler_check.clicked.connect(self.check_emccd_temperature)
        self.QPushButton_emccd_cooler_switch.clicked.connect(self.switch_emccd_cooler)
        self.QDoubleSpinBox_stage_x.valueChanged.connect(self.Signal_piezo_move_x.emit)
        self.QDoubleSpinBox_stage_y.valueChanged.connect(self.Signal_piezo_move_y.emit)
        self.QDoubleSpinBox_stage_z.valueChanged.connect(self.Signal_piezo_move_z.emit)
        self.QPushButton_move_deck_up.clicked.connect(self.deck_move_up)
        self.QPushButton_move_deck_down.clicked.connect(self.deck_move_down)
        self.QPushButton_move_deck.clicked.connect(self.deck_move)
        self.QDoubleSpinBox_galvo_x.valueChanged.connect(self.Signal_galvo_scan.emit)
        self.QDoubleSpinBox_galvo_y.valueChanged.connect(self.Signal_galvo_scan.emit)
        self.QPushButton_plot_trigger.clicked.connect(self.plot_trigger_sequence)
        self.QPushButton_video.clicked.connect(self.video)
        self.QPushButton_fft.clicked.connect(self.run_fft)
        self.QPushButton_plot_profile.clicked.connect(self.run_plot_profile)
        self.QPushButton_save.clicked.connect(self.save)
        self.QPushButton_laser_488_0.clicked.connect(self.set_laser_488_0)
        self.QPushButton_laser_488_1.clicked.connect(self.set_laser_488_1)
        self.QPushButton_laser_488_2.clicked.connect(self.set_laser_488_2)
        self.QPushButton_laser_405.clicked.connect(self.set_laser_405)
        self.QPushButton_2d_resolft.clicked.connect(self.resolft_2d)
        # self.QPushButton_3d_resolft.clicked.connect(self.resolft_3d)
        self.QPushButton_galvo_scan.clicked.connect(self.galvo_scan)
        self.QPushButton_2d_beadscan.clicked.connect(self.beadscan_2d)
        self.QComboBox_trigger_parameter.currentIndexChanged.connect(self.update_trigger_parameter_sets)

    def check_emccd_temperature(self):
        self.Signal_check_emccd_temperature.emit()

    def switch_emccd_cooler(self, checked):
        if checked:
            self.QPushButton_emccd_cooler_switch.setText("Cooler ON")
            self.Signal_switch_emccd_cooler_on.emit()
            print("Cooler is ON")
        else:
            self.QPushButton_emccd_cooler_switch.setText("Cooler OFF")
            self.Signal_switch_emccd_cooler_off.emit()
            print("Cooler is OFF")


    def deck_move_up(self):
        self.Signal_deck_up.emit()

    def deck_move_down(self):
        self.Signal_deck_down.emit()

    def deck_move(self):
        if self.QPushButton_move_deck.isChecked():
            self.Signal_deck_move.emit()
        else:
            self.Signal_deck_move_stop.emit()

    def set_laser_488_0(self):
        if self.QPushButton_laser_488_0.isChecked():
            self.Signal_setlaseron_488_0.emit()
        else:
            self.Signal_setlaseroff_488_0.emit()

    def set_laser_488_1(self):
        if self.QPushButton_laser_488_1.isChecked():
            self.Signal_setlaseron_488_1.emit()
        else:
            self.Signal_setlaseroff_488_1.emit()

    def set_laser_488_2(self):
        if self.QPushButton_laser_488_2.isChecked():
            self.Signal_setlaseron_488_2.emit()
        else:
            self.Signal_setlaseroff_488_2.emit()

    def set_laser_405(self):
        if self.QPushButton_laser_405.isChecked():
            self.Signal_setlaseron_405.emit()
        else:
            self.Signal_setlaseroff_405.emit()

    def plot_trigger_sequence(self):
        self.Signal_plot_trigger.emit()

    def video(self):
        if self.QPushButton_video.isChecked():
            self.Signal_start_video.emit()
            self.QPushButton_fft.setEnabled(True)
            self.QPushButton_plot_profile.setEnabled(True)
            self.QPushButton_2d_resolft.setEnabled(False)
            # self.QPushButton_3d_resolft.setEnabled(False)
            self.QPushButton_2d_beadscan.setEnabled(False)
            # self.QPushButton_3d_beadscan.setEnabled(False)
            self.QPushButton_galvo_scan.setEnabled(False)
        else:
            self.Signal_stop_video.emit()
            if self.QPushButton_fft.isChecked():
                self.Signal_stop_plot_profile.emit()
            self.QPushButton_fft.setEnabled(False)
            self.QPushButton_fft.setChecked(False)
            if self.QPushButton_plot_profile.isChecked():
                self.Signal_stop_plot_profile.emit()
            self.QPushButton_plot_profile.setEnabled(False)
            self.QPushButton_plot_profile.setChecked(False)
            self.QPushButton_2d_resolft.setEnabled(True)
            # self.QPushButton_3d_resolft.setEnabled(True)
            self.QPushButton_2d_beadscan.setEnabled(True)
            # self.QPushButton_3d_beadscan.setEnabled(True)
            self.QPushButton_galvo_scan.setEnabled(True)

    def run_fft(self):
        if self.QPushButton_fft.isChecked():
            self.Signal_run_fft.emit()
        else:
            self.Signal_stop_fft.emit()

    def run_plot_profile(self):
        if self.QPushButton_plot_profile.isChecked():
            self.Signal_run_plot_profile.emit()
        else:
            self.Signal_stop_plot_profile.emit()

    def save(self):
        dialog = cw.create_file_dialogue(name="Save File", file_filter="All Files (*)",
                                         default_dir=r"C:/Users/ruizhe.lin/Documents/data")
        if dialog.exec_() == QtWidgets.QFileDialog.Accepted:
            selected_file = dialog.selectedFiles()
            if selected_file:
                print(selected_file[0])
                self.Signal_save_file.emit(selected_file[0])

    def resolft_2d(self):
        self.Signal_2d_resolft.emit()

    # def resolft_3d(self):
    #     self.Signal_3d_resolft.emit()

    def beadscan_2d(self):
        self.Signal_beadscan_2d.emit()

    # def beadscan_3d(self):
    #     self.Signal_beadscan_3d.emit()

    def galvo_scan(self):
        self.Signal_galvo_scan.emit()

    def update_trigger_parameter_sets(self):
        presets = self.QComboBox_trigger_parameter.currentText()
        if presets == 'Default':
            self.QDoubleSpinBox_cycle_period.setValue(0.100)
            self.QDoubleSpinBox_piezo_start.setValue(0.050)
            self.QDoubleSpinBox_start_x.setValue(0.000)
            self.QDoubleSpinBox_start_y.setValue(0.000)
            self.QDoubleSpinBox_start_z.setValue(0.000)
            self.QDoubleSpinBox_step_x.setValue(0.040)
            self.QDoubleSpinBox_step_y.setValue(0.040)
            self.QDoubleSpinBox_step_z.setValue(0.040)
            self.QDoubleSpinBox_range_x.setValue(1.000)
            self.QDoubleSpinBox_range_y.setValue(1.000)
            self.QDoubleSpinBox_range_z.setValue(0.600)
            self.QDoubleSpinBox_ttl_start_on_405.setValue(0.005)
            self.QDoubleSpinBox_ttl_stop_on_405.setValue(0.010)
            self.QDoubleSpinBox_ttl_start_off_488_0.setValue(0.012)
            self.QDoubleSpinBox_ttl_stop_off_488_0.setValue(0.017)
            self.QDoubleSpinBox_ttl_start_off_488_1.setValue(0.012)
            self.QDoubleSpinBox_ttl_stop_off_488_1.setValue(0.017)
            self.QDoubleSpinBox_ttl_start_read_488_2.setValue(0.020)
            self.QDoubleSpinBox_ttl_stop_read_488_2.setValue(0.040)
            self.QDoubleSpinBox_ttl_start_camera_main.setValue(0.020)
            self.QDoubleSpinBox_ttl_stop_camera_main.setValue(0.040)
            self.QDoubleSpinBox_ttl_start_camera_wfs.setValue(0.000)
            self.QDoubleSpinBox_ttl_stop_camera_wfs.setValue(0.000)
        if presets == 'Live':
            self.QDoubleSpinBox_cycle_period.setValue(0.100)
            self.QDoubleSpinBox_piezo_start.setValue(0.080)
            self.QDoubleSpinBox_start_x.setValue(0.000)
            self.QDoubleSpinBox_start_y.setValue(0.000)
            self.QDoubleSpinBox_start_z.setValue(0.000)
            self.QDoubleSpinBox_step_x.setValue(0.000)
            self.QDoubleSpinBox_step_y.setValue(0.000)
            self.QDoubleSpinBox_step_z.setValue(0.000)
            self.QDoubleSpinBox_range_x.setValue(0.000)
            self.QDoubleSpinBox_range_y.setValue(0.000)
            self.QDoubleSpinBox_range_z.setValue(0.000)
            self.QDoubleSpinBox_ttl_start_on_405.setValue(0.005)
            self.QDoubleSpinBox_ttl_stop_on_405.setValue(0.010)
            self.QDoubleSpinBox_ttl_start_off_488_0.setValue(0.015)
            self.QDoubleSpinBox_ttl_stop_off_488_0.setValue(0.080)
            self.QDoubleSpinBox_ttl_start_off_488_1.setValue(0.015)
            self.QDoubleSpinBox_ttl_stop_off_488_1.setValue(0.080)
            self.QDoubleSpinBox_ttl_start_read_488_2.setValue(0.015)
            self.QDoubleSpinBox_ttl_stop_read_488_2.setValue(0.080)
            self.QDoubleSpinBox_ttl_start_camera_main.setValue(0.015)
            self.QDoubleSpinBox_ttl_stop_camera_main.setValue(0.080)
            self.QDoubleSpinBox_ttl_start_camera_wfs.setValue(0.000)
            self.QDoubleSpinBox_ttl_stop_camera_wfs.setValue(0.000)
        if presets == 'WFS':
            self.QDoubleSpinBox_cycle_period.setValue(0.100)
            self.QDoubleSpinBox_piezo_start.setValue(0.080)
            self.QDoubleSpinBox_start_x.setValue(0.000)
            self.QDoubleSpinBox_start_y.setValue(0.000)
            self.QDoubleSpinBox_start_z.setValue(0.000)
            self.QDoubleSpinBox_step_x.setValue(0.000)
            self.QDoubleSpinBox_step_y.setValue(0.000)
            self.QDoubleSpinBox_step_z.setValue(0.000)
            self.QDoubleSpinBox_range_x.setValue(0.000)
            self.QDoubleSpinBox_range_y.setValue(0.000)
            self.QDoubleSpinBox_range_z.setValue(0.000)
            self.QDoubleSpinBox_ttl_start_on_405.setValue(0.005)
            self.QDoubleSpinBox_ttl_stop_on_405.setValue(0.010)
            self.QDoubleSpinBox_ttl_start_off_488_0.setValue(0.020)
            self.QDoubleSpinBox_ttl_stop_off_488_0.setValue(0.050)
            self.QDoubleSpinBox_ttl_start_off_488_1.setValue(0.020)
            self.QDoubleSpinBox_ttl_stop_off_488_1.setValue(0.050)
            self.QDoubleSpinBox_ttl_start_read_488_2.setValue(0.020)
            self.QDoubleSpinBox_ttl_stop_read_488_2.setValue(0.050)
            self.QDoubleSpinBox_ttl_start_camera_main.setValue(0.000)
            self.QDoubleSpinBox_ttl_stop_camera_main.setValue(0.000)
            self.QDoubleSpinBox_ttl_start_camera_wfs.setValue(0.020)
            self.QDoubleSpinBox_ttl_stop_camera_wfs.setValue(0.050)
        if presets == 'UseDefined_1':
            self.QDoubleSpinBox_cycle_period.setValue(0.040)
            self.QDoubleSpinBox_piezo_start.setValue(0.030)
            self.QDoubleSpinBox_start_x.setValue(0.000)
            self.QDoubleSpinBox_start_y.setValue(0.000)
            self.QDoubleSpinBox_start_z.setValue(0.000)
            self.QDoubleSpinBox_step_x.setValue(0.030)
            self.QDoubleSpinBox_step_y.setValue(0.030)
            self.QDoubleSpinBox_step_z.setValue(0.080)
            self.QDoubleSpinBox_range_x.setValue(0.600)
            self.QDoubleSpinBox_range_y.setValue(0.600)
            self.QDoubleSpinBox_range_z.setValue(0.800)
            self.QDoubleSpinBox_ttl_start_on_405.setValue(0.002)
            self.QDoubleSpinBox_ttl_stop_on_405.setValue(0.004)
            self.QDoubleSpinBox_ttl_start_off_488_0.setValue(0.007)
            self.QDoubleSpinBox_ttl_stop_off_488_0.setValue(0.010)
            self.QDoubleSpinBox_ttl_start_off_488_1.setValue(0.007)
            self.QDoubleSpinBox_ttl_stop_off_488_1.setValue(0.010)
            self.QDoubleSpinBox_ttl_start_read_488_2.setValue(0.012)
            self.QDoubleSpinBox_ttl_stop_read_488_2.setValue(0.015)
            self.QDoubleSpinBox_ttl_start_camera_main.setValue(0.012)
            self.QDoubleSpinBox_ttl_stop_camera_main.setValue(0.015)
            self.QDoubleSpinBox_ttl_start_camera_wfs.setValue(0.000)
            self.QDoubleSpinBox_ttl_stop_camera_wfs.setValue(0.000)
        if presets == 'UseDefined_2':
            self.QDoubleSpinBox_cycle_period.setValue(0.075)
            self.QDoubleSpinBox_piezo_start.setValue(0.050)
            self.QDoubleSpinBox_start_x.setValue(0.000)
            self.QDoubleSpinBox_start_y.setValue(0.000)
            self.QDoubleSpinBox_start_z.setValue(0.000)
            self.QDoubleSpinBox_step_x.setValue(0.032)
            self.QDoubleSpinBox_step_y.setValue(0.032)
            self.QDoubleSpinBox_step_z.setValue(0.050)
            self.QDoubleSpinBox_range_x.setValue(0.960)
            self.QDoubleSpinBox_range_y.setValue(0.960)
            self.QDoubleSpinBox_range_z.setValue(0.500)
            self.QDoubleSpinBox_ttl_start_on_405.setValue(0.005)
            self.QDoubleSpinBox_ttl_stop_on_405.setValue(0.006)
            self.QDoubleSpinBox_ttl_start_off_488_0.setValue(0.008)
            self.QDoubleSpinBox_ttl_stop_off_488_0.setValue(0.010)
            self.QDoubleSpinBox_ttl_start_off_488_1.setValue(0.008)
            self.QDoubleSpinBox_ttl_stop_off_488_1.setValue(0.010)
            self.QDoubleSpinBox_ttl_start_read_488_2.setValue(0.040)
            self.QDoubleSpinBox_ttl_stop_read_488_2.setValue(0.041)
            self.QDoubleSpinBox_ttl_start_camera_main.setValue(0.040)
            self.QDoubleSpinBox_ttl_stop_camera_main.setValue(0.041)
            self.QDoubleSpinBox_ttl_start_camera_wfs.setValue(0.000)
            self.QDoubleSpinBox_ttl_stop_camera_wfs.setValue(0.000)


import sys

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = ConWidget()
    window.show()
    sys.exit(app.exec_())
